// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250629104357_WorkScheduleUpdateRangeIngoretUpdatingCreatedAt")]
    partial class WorkScheduleUpdateRangeIngoretUpdatingCreatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Common.Appointment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal?>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTimeExpected")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceExpected")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceFull")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Domain.Entities.Common.Media", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("Domain.Entities.Common.WorkSchedule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<TimeOnly?>("BreakEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("BreakStartTime")
                        .HasColumnType("time");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("bit");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("UserID");

                    b.ToTable("WorkSchedules");
                });

            modelBuilder.Entity("Domain.Entities.Common.WorkScheduleException", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFullDay")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserAccountID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("UserAccountID");

                    b.ToTable("WorkScheduleExceptions");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IN")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("IN")
                        .IsUnique();

                    b.HasIndex("LocationID")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasFilter("[Phone] IS NOT NULL");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.CompanyFAQ", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("CompanyFAQs");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.CompanyFAQCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("Name");

                    b.ToTable("CompanyFAQCategories");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.CompanyInvitation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAccountID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasFilter("[Token] IS NOT NULL");

                    b.ToTable("CompanyInvitations");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.CompanyMedia", b =>
                {
                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("MediaID")
                        .HasColumnType("int");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.HasKey("CompanyID", "MediaID");

                    b.HasIndex("MediaID");

                    b.ToTable("CompanyMedias");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.Service", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Domain.Entities.LocationReleated.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("Flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("WikiDataId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_City_Name");

                    b.HasIndex("StateId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Domain.Entities.LocationReleated.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Capital")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Currency")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CurrencyName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CurrencySymbol")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Emoji")
                        .HasMaxLength(191)
                        .HasColumnType("nvarchar(191)");

                    b.Property<string>("EmojiU")
                        .HasMaxLength(191)
                        .HasColumnType("nvarchar(191)");

                    b.Property<bool>("Flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Iso2")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Iso3")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Native")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NumericCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("PhoneCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("Subregion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubregionId")
                        .HasColumnType("int");

                    b.Property<string>("Timezones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tld")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Translations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("WikiDataId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Country_Name");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Domain.Entities.LocationReleated.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Domain.Entities.LocationReleated.State", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FipsCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iso2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WikiDataId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CountryId");

                    b.ToTable("States");
                });

            modelBuilder.Entity("Domain.Entities.User.Permission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "UserCreate"
                        },
                        new
                        {
                            ID = 2,
                            Name = "UserRead"
                        },
                        new
                        {
                            ID = 3,
                            Name = "UserUpdate"
                        },
                        new
                        {
                            ID = 4,
                            Name = "UserDelete"
                        },
                        new
                        {
                            ID = 5,
                            Name = "CompanyCreate"
                        },
                        new
                        {
                            ID = 6,
                            Name = "CompanyRead"
                        },
                        new
                        {
                            ID = 7,
                            Name = "CompanyUpdate"
                        },
                        new
                        {
                            ID = 8,
                            Name = "CompanyDelete"
                        },
                        new
                        {
                            ID = 9,
                            Name = "ReportView"
                        },
                        new
                        {
                            ID = 10,
                            Name = "SettingsManage"
                        },
                        new
                        {
                            ID = 11,
                            Name = "WorkScheduleCompanyRead"
                        },
                        new
                        {
                            ID = 12,
                            Name = "WorkScheduleCompanyCreate"
                        },
                        new
                        {
                            ID = 13,
                            Name = "WorkScheduleCompanyUpdate"
                        },
                        new
                        {
                            ID = 14,
                            Name = "WorkScheduleCompanyExceptionManage"
                        },
                        new
                        {
                            ID = 15,
                            Name = "WorkScheduleUserRead"
                        },
                        new
                        {
                            ID = 16,
                            Name = "WorkScheduleUserCreate"
                        },
                        new
                        {
                            ID = 17,
                            Name = "WorkScheduleUserUpdate"
                        },
                        new
                        {
                            ID = 18,
                            Name = "WorkScheduleUserExceptionManage"
                        },
                        new
                        {
                            ID = 19,
                            Name = "ServiceCreate"
                        },
                        new
                        {
                            ID = 20,
                            Name = "ServiceRead"
                        },
                        new
                        {
                            ID = 21,
                            Name = "ServiceUpdate"
                        },
                        new
                        {
                            ID = 22,
                            Name = "ServiceDelete"
                        },
                        new
                        {
                            ID = 23,
                            Name = "AppointmentSchedule"
                        },
                        new
                        {
                            ID = 24,
                            Name = "AppointmentRead"
                        },
                        new
                        {
                            ID = 25,
                            Name = "AppointmentUpdate"
                        },
                        new
                        {
                            ID = 26,
                            Name = "AppointmentCancel"
                        },
                        new
                        {
                            ID = 27,
                            Name = "AppointmentApprove"
                        },
                        new
                        {
                            ID = 28,
                            Name = "MediaUpload"
                        },
                        new
                        {
                            ID = 29,
                            Name = "MediaRead"
                        },
                        new
                        {
                            ID = 30,
                            Name = "MediaDelete"
                        },
                        new
                        {
                            ID = 31,
                            Name = "CompanyMediaUpload"
                        },
                        new
                        {
                            ID = 32,
                            Name = "CompanyMediaRead"
                        },
                        new
                        {
                            ID = 33,
                            Name = "CompanyMediaDelete"
                        },
                        new
                        {
                            ID = 34,
                            Name = "FaqCreate"
                        },
                        new
                        {
                            ID = 35,
                            Name = "FaqRead"
                        },
                        new
                        {
                            ID = 36,
                            Name = "FaqUpdate"
                        },
                        new
                        {
                            ID = 37,
                            Name = "FaqDelete"
                        },
                        new
                        {
                            ID = 38,
                            Name = "FaqCategoryCreate"
                        },
                        new
                        {
                            ID = 39,
                            Name = "FaqCategoryRead"
                        },
                        new
                        {
                            ID = 40,
                            Name = "FaqCategoryUpdate"
                        },
                        new
                        {
                            ID = 41,
                            Name = "FaqCategoryDelete"
                        },
                        new
                        {
                            ID = 42,
                            Name = "InvitationSend"
                        },
                        new
                        {
                            ID = 43,
                            Name = "InvitationRead"
                        },
                        new
                        {
                            ID = 44,
                            Name = "InvitationRevoke"
                        },
                        new
                        {
                            ID = 45,
                            Name = "LocationRead"
                        },
                        new
                        {
                            ID = 46,
                            Name = "CityRead"
                        },
                        new
                        {
                            ID = 47,
                            Name = "StateRead"
                        },
                        new
                        {
                            ID = 48,
                            Name = "CountryRead"
                        },
                        new
                        {
                            ID = 49,
                            Name = "RoleCreate"
                        },
                        new
                        {
                            ID = 50,
                            Name = "RoleRead"
                        },
                        new
                        {
                            ID = 51,
                            Name = "RoleUpdate"
                        },
                        new
                        {
                            ID = 52,
                            Name = "RoleDelete"
                        },
                        new
                        {
                            ID = 53,
                            Name = "RolePermissionManage"
                        },
                        new
                        {
                            ID = 54,
                            Name = "UserLoginDataRead"
                        },
                        new
                        {
                            ID = 55,
                            Name = "UserLoginDataManage"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User.Role", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            ID = 2,
                            Name = "PublicUser"
                        },
                        new
                        {
                            ID = 3,
                            Name = "CompanyAdmin"
                        },
                        new
                        {
                            ID = 4,
                            Name = "CompanyMember"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User.RolePermission", b =>
                {
                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int>("PermissionID")
                        .HasColumnType("int");

                    b.HasKey("RoleID", "PermissionID");

                    b.HasIndex("PermissionID");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            PermissionID = 1
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 2
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 3
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 4
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 5
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 6
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 7
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 8
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 9
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 10
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 12
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 11
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 13
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 14
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 16
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 15
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 17
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 18
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 19
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 20
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 21
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 22
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 23
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 24
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 25
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 26
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 27
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 49
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 50
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 51
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 52
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 53
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 34
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 35
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 36
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 37
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 38
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 39
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 40
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 41
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 42
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 43
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 44
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 31
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 32
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 33
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 6
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 7
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 8
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 12
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 11
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 13
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 14
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 16
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 15
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 17
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 18
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 19
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 20
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 21
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 22
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 24
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 27
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 34
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 35
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 36
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 37
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 38
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 39
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 40
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 41
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 42
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 43
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 44
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 31
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 32
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 33
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 15
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 16
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 17
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 18
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 23
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 24
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 26
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 20
                        },
                        new
                        {
                            RoleID = 2,
                            PermissionID = 6
                        },
                        new
                        {
                            RoleID = 2,
                            PermissionID = 20
                        },
                        new
                        {
                            RoleID = 2,
                            PermissionID = 23
                        },
                        new
                        {
                            RoleID = 2,
                            PermissionID = 24
                        });
                });

            modelBuilder.Entity("Domain.Entities.User.UserAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("RoleID");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("Domain.Entities.User.UserLoginData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ConfirmationToken")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varbinary(255)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PendingNewEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RecoveryToken")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("RecoveryTokenExpTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAccountID")
                        .HasColumnType("int");

                    b.Property<int>("VerificationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("VerificationTokenExpTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PendingNewEmail")
                        .IsUnique()
                        .HasFilter("[PendingNewEmail] IS NOT NULL");

                    b.HasIndex("UserAccountID")
                        .IsUnique();

                    b.ToTable("UserLoginDatas");
                });

            modelBuilder.Entity("Domain.Entities.Common.Appointment", b =>
                {
                    b.HasOne("Domain.Entities.User.UserAccount", "Client")
                        .WithMany("AppointmentsAsClient")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CompanyReleated.Company", "Company")
                        .WithMany("Appointments")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.User.UserAccount", "Employee")
                        .WithMany("AppointmentsAsEmployee")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Company");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.Common.WorkSchedule", b =>
                {
                    b.HasOne("Domain.Entities.CompanyReleated.Company", "Company")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User.UserAccount", "User")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Common.WorkScheduleException", b =>
                {
                    b.HasOne("Domain.Entities.CompanyReleated.Company", "Company")
                        .WithMany("WorkScheduleExceptions")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User.UserAccount", "UserAccount")
                        .WithMany("WorkScheduleExceptions")
                        .HasForeignKey("UserAccountID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.Company", b =>
                {
                    b.HasOne("Domain.Entities.LocationReleated.Location", "Location")
                        .WithOne("Company")
                        .HasForeignKey("Domain.Entities.CompanyReleated.Company", "LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.CompanyFAQ", b =>
                {
                    b.HasOne("Domain.Entities.CompanyReleated.CompanyFAQCategory", "Category")
                        .WithMany("FAQs")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.CompanyFAQCategory", b =>
                {
                    b.HasOne("Domain.Entities.CompanyReleated.Company", "Company")
                        .WithMany("CompanyFAQCategories")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.CompanyInvitation", b =>
                {
                    b.HasOne("Domain.Entities.CompanyReleated.Company", "Company")
                        .WithMany("Invitations")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.CompanyMedia", b =>
                {
                    b.HasOne("Domain.Entities.CompanyReleated.Company", "Company")
                        .WithMany("CompanyMedias")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Common.Media", "Media")
                        .WithMany("CompanyMedias")
                        .HasForeignKey("MediaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.Service", b =>
                {
                    b.HasOne("Domain.Entities.CompanyReleated.Company", "Company")
                        .WithMany("Services")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Entities.LocationReleated.City", b =>
                {
                    b.HasOne("Domain.Entities.LocationReleated.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.LocationReleated.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Domain.Entities.LocationReleated.State", b =>
                {
                    b.HasOne("Domain.Entities.LocationReleated.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Domain.Entities.User.RolePermission", b =>
                {
                    b.HasOne("Domain.Entities.User.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.User.UserAccount", b =>
                {
                    b.HasOne("Domain.Entities.CompanyReleated.Company", "Company")
                        .WithMany("UserAccounts")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.User.Role", "Role")
                        .WithMany("UserAccounts")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.User.UserLoginData", b =>
                {
                    b.HasOne("Domain.Entities.User.UserAccount", "UserAccount")
                        .WithOne("UserLoginData")
                        .HasForeignKey("Domain.Entities.User.UserLoginData", "UserAccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Domain.Entities.Common.Media", b =>
                {
                    b.Navigation("CompanyMedias");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.Company", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("CompanyFAQCategories");

                    b.Navigation("CompanyMedias");

                    b.Navigation("Invitations");

                    b.Navigation("Services");

                    b.Navigation("UserAccounts");

                    b.Navigation("WorkScheduleExceptions");

                    b.Navigation("WorkSchedules");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.CompanyFAQCategory", b =>
                {
                    b.Navigation("FAQs");
                });

            modelBuilder.Entity("Domain.Entities.LocationReleated.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("States");
                });

            modelBuilder.Entity("Domain.Entities.LocationReleated.Location", b =>
                {
                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Entities.LocationReleated.State", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Domain.Entities.User.Role", b =>
                {
                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("Domain.Entities.User.UserAccount", b =>
                {
                    b.Navigation("AppointmentsAsClient");

                    b.Navigation("AppointmentsAsEmployee");

                    b.Navigation("UserLoginData");

                    b.Navigation("WorkScheduleExceptions");

                    b.Navigation("WorkSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
