// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260302164103_ChangedIDPKEntityNameToId")]
    partial class ChangedIDPKEntityNameToId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.BranchReleated.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveStatus")
                        .HasColumnType("int");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(23, 15)
                        .HasColumnType("decimal(23,15)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(24, 15)
                        .HasColumnType("decimal(24,15)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Domain.Entities.BranchReleated.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("Flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("WikiDataId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_City_Name");

                    b.HasIndex("StateId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Domain.Entities.BranchReleated.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Capital")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Currency")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CurrencyName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CurrencySymbol")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Emoji")
                        .HasMaxLength(191)
                        .HasColumnType("nvarchar(191)");

                    b.Property<string>("EmojiU")
                        .HasMaxLength(191)
                        .HasColumnType("nvarchar(191)");

                    b.Property<bool>("Flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Iso2")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Iso3")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Native")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NumericCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("PhoneCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("Subregion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubregionId")
                        .HasColumnType("int");

                    b.Property<string>("Timezones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tld")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Translations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("WikiDataId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Country_Name");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Domain.Entities.BranchReleated.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FipsCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Iso2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StateCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .HasMaxLength(191)
                        .HasColumnType("nvarchar(191)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("WikiDataId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_State_Name");

                    b.ToTable("States");
                });

            modelBuilder.Entity("Domain.Entities.Common.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("ClientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal?>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTimeExpected")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("PriceExpected")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceFull")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("ServiceID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ClientID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("ServiceID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Domain.Entities.Common.BookingGuestInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ContactType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("ContactType", "Contact");

                    b.ToTable("BookingGuestInfos");
                });

            modelBuilder.Entity("Domain.Entities.Common.BookingVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PendingNewContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VerificationType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("VerificationType");

                    b.ToTable("BookingVerifications");
                });

            modelBuilder.Entity("Domain.Entities.Common.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RemoteUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OriginalUrl");

                    b.HasIndex("RemoteUrl");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("Domain.Entities.Common.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("MaxBookingsPerMonth")
                        .HasColumnType("int");

                    b.Property<int>("MaxBranches")
                        .HasColumnType("int");

                    b.Property<int>("MaxEmployees")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("PriceMonthly")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("Domain.Entities.Common.WorkSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAccountID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountID");

                    b.ToTable("WorkSchedules");
                });

            modelBuilder.Entity("Domain.Entities.Common.WorkScheduleException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAccountID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountID");

                    b.ToTable("WorkScheduleExceptions");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IN")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Viewed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("IN")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasFilter("[Phone] IS NOT NULL");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.CompanyFAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveStatus")
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.ToTable("CompanyFAQs");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.CompanyFAQCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveStatus")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyID");

                    b.ToTable("CompanyFAQCategories");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.CompanyInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAccountID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyID");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasFilter("[Token] IS NOT NULL");

                    b.ToTable("CompanyInvitations");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.CompanyMedia", b =>
                {
                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("MediaID")
                        .HasColumnType("int");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.HasKey("CompanyID", "MediaID");

                    b.HasIndex("MediaID");

                    b.ToTable("CompanyMedia");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.CompanySubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("bit");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("CompanySubscriptions");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveStatus")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyID");

                    b.HasIndex("Name");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Domain.Entities.ReviewReleated.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Accuracy")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("CheckIn")
                        .HasColumnType("int");

                    b.Property<int?>("Cleanliness")
                        .HasColumnType("int");

                    b.Property<int?>("Communication")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Locale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Location")
                        .HasColumnType("int");

                    b.Property<int>("Overall")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ReviewInviteId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewInviteId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Domain.Entities.ReviewReleated.ReviewInvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<bool>("ClientReviewed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CloseAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTimeOffset>("OpenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("ReviewInvites");
                });

            modelBuilder.Entity("Domain.Entities.ReviewReleated.ReviewMedia", b =>
                {
                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.Property<int>("MediaId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId", "MediaId");

                    b.HasIndex("MediaId");

                    b.ToTable("ReviewMedia");
                });

            modelBuilder.Entity("Domain.Entities.User.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "UserCreate"
                        },
                        new
                        {
                            Id = 2,
                            Name = "UserRead"
                        },
                        new
                        {
                            Id = 3,
                            Name = "UserUpdate"
                        },
                        new
                        {
                            Id = 4,
                            Name = "UserDelete"
                        },
                        new
                        {
                            Id = 5,
                            Name = "CompanyCreate"
                        },
                        new
                        {
                            Id = 6,
                            Name = "CompanyRead"
                        },
                        new
                        {
                            Id = 7,
                            Name = "CompanyUpdate"
                        },
                        new
                        {
                            Id = 8,
                            Name = "CompanyUpdatePartial"
                        },
                        new
                        {
                            Id = 9,
                            Name = "CompanyUpdateFull"
                        },
                        new
                        {
                            Id = 10,
                            Name = "CompanyDelete"
                        },
                        new
                        {
                            Id = 11,
                            Name = "CompanyReadAll"
                        },
                        new
                        {
                            Id = 12,
                            Name = "CompanyReadOwn"
                        },
                        new
                        {
                            Id = 13,
                            Name = "CompanyReadLimited"
                        },
                        new
                        {
                            Id = 14,
                            Name = "CompanyEmployeeCreate"
                        },
                        new
                        {
                            Id = 15,
                            Name = "CompanyEmployeeRead"
                        },
                        new
                        {
                            Id = 16,
                            Name = "CompanyEmployeeUpdate"
                        },
                        new
                        {
                            Id = 17,
                            Name = "CompanyEmployeeDelete"
                        },
                        new
                        {
                            Id = 18,
                            Name = "ReportView"
                        },
                        new
                        {
                            Id = 19,
                            Name = "SettingsManage"
                        },
                        new
                        {
                            Id = 20,
                            Name = "WorkScheduleUserCreate"
                        },
                        new
                        {
                            Id = 21,
                            Name = "WorkScheduleUserUpdate"
                        },
                        new
                        {
                            Id = 22,
                            Name = "WorkScheduleUserDelete"
                        },
                        new
                        {
                            Id = 23,
                            Name = "WorkScheduleExceptionUserCreate"
                        },
                        new
                        {
                            Id = 24,
                            Name = "WorkScheduleExceptionUserUpdate"
                        },
                        new
                        {
                            Id = 25,
                            Name = "WorkScheduleExceptionUserDelete"
                        },
                        new
                        {
                            Id = 26,
                            Name = "ServiceCreate"
                        },
                        new
                        {
                            Id = 27,
                            Name = "ServiceRead"
                        },
                        new
                        {
                            Id = 28,
                            Name = "ServiceUpdate"
                        },
                        new
                        {
                            Id = 29,
                            Name = "ServiceDelete"
                        },
                        new
                        {
                            Id = 30,
                            Name = "BookingCreate"
                        },
                        new
                        {
                            Id = 31,
                            Name = "BookingRead"
                        },
                        new
                        {
                            Id = 32,
                            Name = "BookingUpdate"
                        },
                        new
                        {
                            Id = 33,
                            Name = "BookingDelete"
                        },
                        new
                        {
                            Id = 34,
                            Name = "BookingCancel"
                        },
                        new
                        {
                            Id = 35,
                            Name = "BookingApprove"
                        },
                        new
                        {
                            Id = 36,
                            Name = "BookingResendCode"
                        },
                        new
                        {
                            Id = 37,
                            Name = "BookingVerify"
                        },
                        new
                        {
                            Id = 38,
                            Name = "MediaUpload"
                        },
                        new
                        {
                            Id = 39,
                            Name = "MediaRead"
                        },
                        new
                        {
                            Id = 40,
                            Name = "MediaDelete"
                        },
                        new
                        {
                            Id = 41,
                            Name = "CompanyMediaUpload"
                        },
                        new
                        {
                            Id = 42,
                            Name = "CompanyMediaRead"
                        },
                        new
                        {
                            Id = 43,
                            Name = "CompanyMediaDelete"
                        },
                        new
                        {
                            Id = 44,
                            Name = "CompanyMediaUpdate"
                        },
                        new
                        {
                            Id = 45,
                            Name = "FaqCreate"
                        },
                        new
                        {
                            Id = 46,
                            Name = "FaqRead"
                        },
                        new
                        {
                            Id = 47,
                            Name = "FaqUpdate"
                        },
                        new
                        {
                            Id = 48,
                            Name = "FaqDelete"
                        },
                        new
                        {
                            Id = 49,
                            Name = "FaqCategoryCreate"
                        },
                        new
                        {
                            Id = 50,
                            Name = "FaqCategoryRead"
                        },
                        new
                        {
                            Id = 51,
                            Name = "FaqCategoryUpdate"
                        },
                        new
                        {
                            Id = 52,
                            Name = "FaqCategoryDelete"
                        },
                        new
                        {
                            Id = 53,
                            Name = "InvitationSend"
                        },
                        new
                        {
                            Id = 54,
                            Name = "InvitationRead"
                        },
                        new
                        {
                            Id = 55,
                            Name = "InvitationRevoke"
                        },
                        new
                        {
                            Id = 56,
                            Name = "BranchRead"
                        },
                        new
                        {
                            Id = 57,
                            Name = "BranchCreate"
                        },
                        new
                        {
                            Id = 58,
                            Name = "BranchUpdate"
                        },
                        new
                        {
                            Id = 59,
                            Name = "BranchDelete"
                        },
                        new
                        {
                            Id = 60,
                            Name = "BranchDisable"
                        },
                        new
                        {
                            Id = 61,
                            Name = "BranchEnable"
                        },
                        new
                        {
                            Id = 62,
                            Name = "CityRead"
                        },
                        new
                        {
                            Id = 63,
                            Name = "StateRead"
                        },
                        new
                        {
                            Id = 64,
                            Name = "CountryRead"
                        },
                        new
                        {
                            Id = 65,
                            Name = "RoleCreate"
                        },
                        new
                        {
                            Id = 66,
                            Name = "RoleRead"
                        },
                        new
                        {
                            Id = 67,
                            Name = "RoleUpdate"
                        },
                        new
                        {
                            Id = 68,
                            Name = "RoleDelete"
                        },
                        new
                        {
                            Id = 69,
                            Name = "RolePermissionManage"
                        },
                        new
                        {
                            Id = 70,
                            Name = "UserLoginDataRead"
                        },
                        new
                        {
                            Id = 71,
                            Name = "UserLoginDataManage"
                        },
                        new
                        {
                            Id = 72,
                            Name = "ReviewCreate"
                        },
                        new
                        {
                            Id = 73,
                            Name = "ReviewInviteCreate"
                        },
                        new
                        {
                            Id = 74,
                            Name = "ReviewInviteRead"
                        },
                        new
                        {
                            Id = 75,
                            Name = "ReviewInviteReadLimited"
                        },
                        new
                        {
                            Id = 76,
                            Name = "SubscriptionPlanUpdate"
                        },
                        new
                        {
                            Id = 77,
                            Name = "CompanySubscriptionUpdate"
                        },
                        new
                        {
                            Id = 78,
                            Name = "CompanySubscriptionGet"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User.Role", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            ID = 2,
                            Name = "PublicUser"
                        },
                        new
                        {
                            ID = 3,
                            Name = "CompanyAdmin"
                        },
                        new
                        {
                            ID = 4,
                            Name = "CompanyEmployee"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User.RolePermission", b =>
                {
                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int>("PermissionID")
                        .HasColumnType("int");

                    b.HasKey("RoleID", "PermissionID");

                    b.HasIndex("PermissionID");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            PermissionID = 1
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 2
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 3
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 4
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 5
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 6
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 7
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 9
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 10
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 11
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 12
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 13
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 14
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 15
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 16
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 17
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 18
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 19
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 20
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 21
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 22
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 23
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 24
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 25
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 26
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 27
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 28
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 29
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 30
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 31
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 32
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 33
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 34
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 35
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 36
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 37
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 57
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 59
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 58
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 60
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 61
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 65
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 66
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 67
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 68
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 69
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 45
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 46
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 47
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 48
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 49
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 50
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 51
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 52
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 53
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 54
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 55
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 41
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 42
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 43
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 44
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 8
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 73
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 74
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 75
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 76
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 77
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 78
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 6
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 12
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 7
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 10
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 8
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 14
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 15
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 16
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 17
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 20
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 21
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 22
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 23
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 24
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 25
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 26
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 27
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 28
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 29
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 30
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 31
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 32
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 34
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 35
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 36
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 37
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 45
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 46
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 47
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 48
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 49
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 50
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 51
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 52
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 53
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 54
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 55
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 57
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 58
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 60
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 41
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 42
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 43
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 44
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 73
                        },
                        new
                        {
                            RoleID = 3,
                            PermissionID = 75
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 20
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 21
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 22
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 23
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 24
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 25
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 30
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 31
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 32
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 34
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 35
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 36
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 37
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 73
                        },
                        new
                        {
                            RoleID = 4,
                            PermissionID = 75
                        },
                        new
                        {
                            RoleID = 2,
                            PermissionID = 13
                        },
                        new
                        {
                            RoleID = 2,
                            PermissionID = 31
                        },
                        new
                        {
                            RoleID = 2,
                            PermissionID = 72
                        },
                        new
                        {
                            RoleID = 2,
                            PermissionID = 36
                        },
                        new
                        {
                            RoleID = 2,
                            PermissionID = 37
                        },
                        new
                        {
                            RoleID = 2,
                            PermissionID = 75
                        });
                });

            modelBuilder.Entity("Domain.Entities.User.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserLoginDataID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CompanyID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserLoginDataID")
                        .IsUnique();

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("Domain.Entities.User.UserAccountMedia", b =>
                {
                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.Property<int>("MediaId")
                        .HasColumnType("int");

                    b.HasKey("UserAccountId", "MediaId");

                    b.HasIndex("MediaId");

                    b.ToTable("UserAccountMedia");
                });

            modelBuilder.Entity("Domain.Entities.User.UserLoginData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("EmailVerificationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("EmailVerificationTokenExpTime")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varbinary(255)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PendingNewEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PendingNewPhone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("PhoneVerificationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("PhoneVerificationToken")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("PhoneVerificationTokenExpTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecoveryToken")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("RecoveryTokenExpTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PendingNewEmail")
                        .IsUnique()
                        .HasFilter("[PendingNewEmail] IS NOT NULL");

                    b.ToTable("UserLoginDatas");
                });

            modelBuilder.Entity("Domain.Entities.BranchReleated.Branch", b =>
                {
                    b.HasOne("Domain.Entities.CompanyReleated.Company", "Company")
                        .WithMany("Branches")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Entities.BranchReleated.City", b =>
                {
                    b.HasOne("Domain.Entities.BranchReleated.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.BranchReleated.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Domain.Entities.BranchReleated.State", b =>
                {
                    b.HasOne("Domain.Entities.BranchReleated.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Domain.Entities.Common.Booking", b =>
                {
                    b.HasOne("Domain.Entities.BranchReleated.Branch", "Branch")
                        .WithMany("Bookings")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User.UserAccount", "Client")
                        .WithMany("BookingsAsClient")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.User.UserAccount", "Employee")
                        .WithMany("BookingsAsEmployee")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CompanyReleated.Service", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Client");

                    b.Navigation("Employee");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Domain.Entities.Common.BookingGuestInfo", b =>
                {
                    b.HasOne("Domain.Entities.Common.Booking", "Booking")
                        .WithOne("GuestInfo")
                        .HasForeignKey("Domain.Entities.Common.BookingGuestInfo", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Domain.Entities.Common.BookingVerification", b =>
                {
                    b.HasOne("Domain.Entities.Common.Booking", "Booking")
                        .WithMany("Verifications")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Domain.Entities.Common.WorkSchedule", b =>
                {
                    b.HasOne("Domain.Entities.User.UserAccount", "UserAccount")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("UserAccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Domain.Entities.Common.WorkScheduleException", b =>
                {
                    b.HasOne("Domain.Entities.User.UserAccount", "UserAccount")
                        .WithMany("WorkScheduleExceptions")
                        .HasForeignKey("UserAccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.CompanyFAQ", b =>
                {
                    b.HasOne("Domain.Entities.CompanyReleated.CompanyFAQCategory", "Category")
                        .WithMany("FAQs")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.CompanyFAQCategory", b =>
                {
                    b.HasOne("Domain.Entities.CompanyReleated.Company", "Company")
                        .WithMany("CompanyFAQCategories")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.CompanyInvitation", b =>
                {
                    b.HasOne("Domain.Entities.CompanyReleated.Company", "Company")
                        .WithMany("Invitations")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.CompanyMedia", b =>
                {
                    b.HasOne("Domain.Entities.CompanyReleated.Company", "Company")
                        .WithMany("CompanyMedia")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Common.Media", "Media")
                        .WithMany("CompanyMedia")
                        .HasForeignKey("MediaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.CompanySubscription", b =>
                {
                    b.HasOne("Domain.Entities.CompanyReleated.Company", "Company")
                        .WithOne("Subscription")
                        .HasForeignKey("Domain.Entities.CompanyReleated.CompanySubscription", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Common.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("CompanySubscriptions")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.Service", b =>
                {
                    b.HasOne("Domain.Entities.CompanyReleated.Company", "Company")
                        .WithMany("Services")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Entities.ReviewReleated.Review", b =>
                {
                    b.HasOne("Domain.Entities.ReviewReleated.ReviewInvite", "ReviewInvite")
                        .WithOne("Review")
                        .HasForeignKey("Domain.Entities.ReviewReleated.Review", "ReviewInviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewInvite");
                });

            modelBuilder.Entity("Domain.Entities.ReviewReleated.ReviewInvite", b =>
                {
                    b.HasOne("Domain.Entities.Common.Booking", "Booking")
                        .WithOne("ReviewInvite")
                        .HasForeignKey("Domain.Entities.ReviewReleated.ReviewInvite", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Domain.Entities.ReviewReleated.ReviewMedia", b =>
                {
                    b.HasOne("Domain.Entities.Common.Media", "Media")
                        .WithMany("ReviewMedia")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ReviewReleated.Review", "Review")
                        .WithMany("Media")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Domain.Entities.User.RolePermission", b =>
                {
                    b.HasOne("Domain.Entities.User.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.User.UserAccount", b =>
                {
                    b.HasOne("Domain.Entities.BranchReleated.Branch", "Branch")
                        .WithMany("UserAccounts")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.CompanyReleated.Company", "Company")
                        .WithMany("UserAccounts")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.User.Role", "Role")
                        .WithMany("UserAccounts")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User.UserLoginData", "UserLoginData")
                        .WithOne("UserAccount")
                        .HasForeignKey("Domain.Entities.User.UserAccount", "UserLoginDataID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Company");

                    b.Navigation("Role");

                    b.Navigation("UserLoginData");
                });

            modelBuilder.Entity("Domain.Entities.User.UserAccountMedia", b =>
                {
                    b.HasOne("Domain.Entities.Common.Media", "Media")
                        .WithMany("UserAccountMedia")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User.UserAccount", "UserAccount")
                        .WithMany("UserAccountMedia")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Domain.Entities.BranchReleated.Branch", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("Domain.Entities.BranchReleated.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("States");
                });

            modelBuilder.Entity("Domain.Entities.BranchReleated.State", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Domain.Entities.Common.Booking", b =>
                {
                    b.Navigation("GuestInfo");

                    b.Navigation("ReviewInvite")
                        .IsRequired();

                    b.Navigation("Verifications");
                });

            modelBuilder.Entity("Domain.Entities.Common.Media", b =>
                {
                    b.Navigation("CompanyMedia");

                    b.Navigation("ReviewMedia");

                    b.Navigation("UserAccountMedia");
                });

            modelBuilder.Entity("Domain.Entities.Common.SubscriptionPlan", b =>
                {
                    b.Navigation("CompanySubscriptions");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.Company", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("CompanyFAQCategories");

                    b.Navigation("CompanyMedia");

                    b.Navigation("Invitations");

                    b.Navigation("Services");

                    b.Navigation("Subscription");

                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.CompanyFAQCategory", b =>
                {
                    b.Navigation("FAQs");
                });

            modelBuilder.Entity("Domain.Entities.CompanyReleated.Service", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Domain.Entities.ReviewReleated.Review", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("Domain.Entities.ReviewReleated.ReviewInvite", b =>
                {
                    b.Navigation("Review")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.User.Role", b =>
                {
                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("Domain.Entities.User.UserAccount", b =>
                {
                    b.Navigation("BookingsAsClient");

                    b.Navigation("BookingsAsEmployee");

                    b.Navigation("UserAccountMedia");

                    b.Navigation("WorkScheduleExceptions");

                    b.Navigation("WorkSchedules");
                });

            modelBuilder.Entity("Domain.Entities.User.UserLoginData", b =>
                {
                    b.Navigation("UserAccount")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
